name: EnergyExplorer

services:

  dashboard:
    build:
      context: .
      dockerfile: docker/App.Dockerfile
    container_name: dashboard
    volumes:
      - ./data:/data
    environment:
      - DATABASE_PATH=/data/data.db
      - APP_MODE=prod
    ports:
      - "8080:8080"
    restart: no

  backend:
    build:
      context: .
      dockerfile: docker/Backend.Dockerfile
    container_name: backend
    volumes:
      - ./data:/data
    environment:
      - DATABASE_PATH=/data/data.db
      - FETCH_MIN_SLEEP_SECONDS=10800
      - FETCH_MAX_SLEEP_SECONDS=14400
    restart: unless-stopped
