services:
  energy_fetcher:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: energy_fetcher
    volumes:
      - ./data:/data
    environment:
      - DATABASE_PATH=/data/data.db
      - APP_MODE=prod
    ports:
      - "8080:8080"
    restart: no