name: EnergyExplorer

services:
  dashboard:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: dashboard
    environment:
      - BACKEND_URL=http://127.0.0.1:8000
      - APP_MODE=prod
    ports:
      - "8080:8080"
    depends_on:
      - api
    restart: no

  fetch:
    build:
      context: .
      dockerfile: docker/fetch/Dockerfile
    container_name: fetch
    environment:
      - API_URL=http://127.0.0.1:8000
    depends_on:
      - api
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: api
    volumes:
      - ./data:/data
    environment:
      - DATABASE_PATH=/data/data.db
    ports:
      - "8000:8000"
    restart: no
